Fix language is not included in the map wrapper c23w methods
what3words/w3w-android-map-components pull request #35
Opened 2024-10-31 11:07 UTC by phpduy

2024-10-31 11:09 UTC, mani-w3w approved these changes

2024-10-31 11:09 UTC, mani-w3w requested changes
Remember to bump the version number to 1.0.7

2024-10-31 11:48 UTC, mani-w3w approved these changes

2024-11-01 02:33 UTC, kaytran2992 approved these changes
Nice one mate.

2024-11-01 07:21 UTC, QuocNguyen-w3w approved these changes

2024-11-01 07:27 UTC, merged